export const AUTH_REQ="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILUE";
export const SINGUP_REQUEST = "SINGUP_REQUEST";
export const SINGUP_SUCCES = "SINGUP_SUCCES";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";